### ISSUE TITLE
可否增加一下工程描述

### ISSUE THREAD

**Issue by shengmingbuxi** [PieceZhang/My-python-lib#1]
博主，您的代码是要解决一个什么问题呢，我看工程里面既有自适应卡尔曼滤波，也有卡尔曼滤波

**Comment by PieceZhang** [comment]
这些是我平时经常会用到的一些算法和模块，因为一般都是自用，所以没有写很多注释，有时间会补充的。如有需要欢迎取用。

**Comment by shengmingbuxi** [comment]
尊敬的博主：
&nbsp; &nbsp;您好！我从github上下载您关于卡尔曼滤波和sage-husa的代码，用了一些带噪声数据测试了这两部分的代码，发现经卡尔曼滤波和sage-husa滤波后的结果一模一样，更换其他数据测试结果也是一样。我感觉可能是sage-husa部分d值设置的问题，但是目前我还没弄明白博主d值这样设置的原因，您知道是什么问题吗？还望赐教！
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;




生命不息
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PieceZhang/My-python-lib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月25日(星期五) 中午1:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PieceZhang/My-python-lib] 可否增加一下工程描述 (Issue #1)





 
这些是我平时经常会用到的一些算法和模块，因为一般都是自用，所以没有写很多注释，有时间会补充的。如有需要欢迎取用。

**Comment by shengmingbuxi** [comment]
博主，我把我测试的代码放在上一封邮件的附件里




生命不息
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PieceZhang/My-python-lib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月25日(星期五) 中午1:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PieceZhang/My-python-lib] 可否增加一下工程描述 (Issue #1)





 
这些是我平时经常会用到的一些算法和模块，因为一般都是自用，所以没有写很多注释，有时间会补充的。如有需要欢迎取用。

**Comment by PieceZhang** [comment]
> 尊敬的博主： &nbsp; &nbsp;您好！我从github上下载您关于卡尔曼滤波和sage-husa的代码，用了一些带噪声数据测试了这两部分的代码，发现经卡尔曼滤波和sage-husa滤波后的结果一模一样，更换其他数据测试结果也是一样。我感觉可能是sage-husa部分d值设置的问题，但是目前我还没弄明白博主d值这样设置的原因，您知道是什么问题吗？还望赐教！ &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 生命不息 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PieceZhang/My-python-lib" ***@***.***&gt;; 发送时间:&nbsp;2022年11月25日(星期五) 中午1:25 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PieceZhang/My-python-lib] 可否增加一下工程描述 (Issue #1) 这些是我平时经常会用到的一些算法和模块，因为一般都是自用，所以没有写很多注释，有时间会补充的。如有需要欢迎取用。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

计算d值的alpha和beta，以及Q和R的初始值都要根据实际情况修改。

**Comment by shengmingbuxi** [comment]
博主，您好，我看大部分论文关于d值的推导都是基于这个公式来的，

而您代码中关于d值的定义用的d = -beta * np.log(self.time / alpha) / self.time&nbsp; ，为什么要这么改呢，公式中sef.time作用是什么呢，我看其初值设定的为1&nbsp;


生命不息
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月26日(星期六) 晚上11:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PieceZhang/My-python-lib] 可否增加一下工程描述 (Issue #1)





  
尊敬的博主： &nbsp; &nbsp;您好！我从github上下载您关于卡尔曼滤波和sage-husa的代码，用了一些带噪声数据测试了这两部分的代码，发现经卡尔曼滤波和sage-husa滤波后的结果一模一样，更换其他数据测试结果也是一样。我感觉可能是sage-husa部分d值设置的问题，但是目前我还没弄明白博主d值这样设置的原因，您知道是什么问题吗？还望赐教！ &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 生命不息 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PieceZhang/My-python-lib" @.&gt;; 发送时间:&nbsp;2022年11月25日(星期五) 中午1:25 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PieceZhang/My-python-lib] 可否增加一下工程描述 (Issue #1) 这些是我平时经常会用到的一些算法和模块，因为一般都是自用，所以没有写很多注释，有时间会补充的。如有需要欢迎取用。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
计算d值的alpha和beta，以及Q和R的初始值都要根据实际情况修改。

**Comment by PieceZhang** [comment]
这个d的变化函数是我根据当时的项目需要自己定义的，你可以修改。
time记录当前的时间步，即滤波器运行的时间。

**Comment by shengmingbuxi** [comment]
博主，您对Q R初值的设定有没有什么经验可以分享吗




生命不息
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PieceZhang/My-python-lib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月26日(星期六) 晚上11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PieceZhang/My-python-lib] 可否增加一下工程描述 (Issue #1)





  
尊敬的博主： &nbsp; &nbsp;您好！我从github上下载您关于卡尔曼滤波和sage-husa的代码，用了一些带噪声数据测试了这两部分的代码，发现经卡尔曼滤波和sage-husa滤波后的结果一模一样，更换其他数据测试结果也是一样。我感觉可能是sage-husa部分d值设置的问题，但是目前我还没弄明白博主d值这样设置的原因，您知道是什么问题吗？还望赐教！ &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 生命不息 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PieceZhang/My-python-lib" @.&gt;; 发送时间:&nbsp;2022年11月25日(星期五) 中午1:25 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PieceZhang/My-python-lib] 可否增加一下工程描述 (Issue #1) 这些是我平时经常会用到的一些算法和模块，因为一般都是自用，所以没有写很多注释，有时间会补充的。如有需要欢迎取用。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
计算d值的alpha和beta，以及Q和R的初始值都要根据实际情况修改。

**Comment by PieceZhang** [comment]
Q和R决定了增益K的大小，可以参考这篇文章 https://blog.csdn.net/zhuoqingjoking97298/article/details/104133963
其他还请自行Google或百度。
